package br.com.lojaoriodopeixe.visao;

import br.com.lojaoriodopeixe.controle.CalculadoraImpl;
import br.com.lojaoriodopeixe.controle.ParcTableModel;
import br.com.lojaoriodopeixe.utils.Utils;
import br.com.lojaoriodopeixe.modelo.Parcela;
import java.awt.Toolkit;
import java.util.List;
import javax.swing.JOptionPane;

/**
 * Classe de visão CalculadoraViewer.
 *
 * @author Vagner Barbosa (contato@vagnerbarbosa.com)
 *
 * @since 10/11/2017
 *
 * @version 1.0
 */
public class CalculadoraViewer extends javax.swing.JFrame {

    public CalculadoraViewer() {
        initComponents();
        util.centerWindow(this);
    }
    Utils util = new Utils();
    CalculadoraImpl ci = new CalculadoraImpl();
    ParcTableModel f = new ParcTableModel();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        valorVistaLabel = new javax.swing.JLabel();
        valorVista = new javax.swing.JTextField();
        jurosValorLabel = new javax.swing.JLabel();
        valorJuros = new javax.swing.JTextField();
        valorParcelasLabel = new javax.swing.JLabel();
        valorParcelas = new javax.swing.JTextField();
        calcularValor = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        logoLRP = new javax.swing.JLabel();
        barraMenu = new javax.swing.JMenuBar();
        barraMenuArquivo = new javax.swing.JMenu();
        barraMenuItemSair = new javax.swing.JMenuItem();
        barraMenuAjuda = new javax.swing.JMenu();
        barraMenuItemSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora de Juros");
        setIconImage(Toolkit.getDefaultToolkit().getImage("mono.png"));
        setLocationByPlatform(true);
        setResizable(false);

        valorVistaLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        valorVistaLabel.setText("Valor à Vista:");

        valorVista.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        valorVista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorVistaActionPerformed(evt);
            }
        });

        jurosValorLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jurosValorLabel.setText("Juros (%):");

        valorJuros.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        valorJuros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorJurosActionPerformed(evt);
            }
        });

        valorParcelasLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        valorParcelasLabel.setText("Parcelas:");

        valorParcelas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        calcularValor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        calcularValor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculator.png"))); // NOI18N
        calcularValor.setText("Calcular");
        calcularValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularValorActionPerformed(evt);
            }
        });

        jTable1.setModel(f);
        jScrollPane1.setViewportView(jTable1);

        logoLRP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logolrp.png"))); // NOI18N

        barraMenuArquivo.setText("Arquivo");

        barraMenuItemSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        barraMenuItemSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit.png"))); // NOI18N
        barraMenuItemSair.setText("Sair");
        barraMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barraMenuItemSairActionPerformed(evt);
            }
        });
        barraMenuArquivo.add(barraMenuItemSair);

        barraMenu.add(barraMenuArquivo);

        barraMenuAjuda.setText("Ajuda");

        barraMenuItemSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/about-us.png"))); // NOI18N
        barraMenuItemSobre.setText("Sobre");
        barraMenuItemSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barraMenuItemSobreActionPerformed(evt);
            }
        });
        barraMenuAjuda.add(barraMenuItemSobre);

        barraMenu.add(barraMenuAjuda);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(logoLRP)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(valorVistaLabel)
                            .addComponent(jurosValorLabel)
                            .addComponent(valorParcelasLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(valorVista, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            .addComponent(valorJuros)
                            .addComponent(valorParcelas)))
                    .addComponent(calcularValor, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                    .addComponent(jSeparator1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(valorVistaLabel)
                            .addComponent(valorVista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jurosValorLabel)
                            .addComponent(valorJuros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(valorParcelasLabel)
                            .addComponent(valorParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(calcularValor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logoLRP)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void valorVistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorVistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorVistaActionPerformed

    private void valorJurosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorJurosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorJurosActionPerformed

    private void calcularValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularValorActionPerformed
        List<Parcela> parcelas = ci.calculoFinanceiro(Double.valueOf(valorVista.getText()), Double.valueOf(valorJuros.getText()), Integer.valueOf(valorParcelas.getText()));
        f.limpar();
        f.addListaDeParcelas(parcelas);
        for (Parcela parcela : parcelas) {
            System.out.println(parcela.toString());
        }
    }//GEN-LAST:event_calcularValorActionPerformed

    private void barraMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraMenuItemSairActionPerformed
        dispose();
    }//GEN-LAST:event_barraMenuItemSairActionPerformed

    private void barraMenuItemSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraMenuItemSobreActionPerformed
        JOptionPane.showConfirmDialog( null,"Desenvolvido em conjunto por: \n Vagner Barbosa e Solon Diego", "Sobre",JOptionPane.CLOSED_OPTION);
    }//GEN-LAST:event_barraMenuItemSobreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraViewer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenu barraMenuAjuda;
    private javax.swing.JMenu barraMenuArquivo;
    private javax.swing.JMenuItem barraMenuItemSair;
    private javax.swing.JMenuItem barraMenuItemSobre;
    private javax.swing.JButton calcularValor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jurosValorLabel;
    private javax.swing.JLabel logoLRP;
    private javax.swing.JTextField valorJuros;
    private javax.swing.JTextField valorParcelas;
    private javax.swing.JLabel valorParcelasLabel;
    private javax.swing.JTextField valorVista;
    private javax.swing.JLabel valorVistaLabel;
    // End of variables declaration//GEN-END:variables
}
