package br.com.lojaoriodopeixe.visao;

import br.com.lojaoriodopeixe.controle.Calculadora;
import br.com.lojaoriodopeixe.controle.CalculadoraImpl;
import br.com.lojaoriodopeixe.utils.FuncTableModelPrestacoes;
import br.com.lojaoriodopeixe.modelo.ParcelaPrestacoes;
import br.com.lojaoriodopeixe.utils.Utils;
import java.awt.Color;
import java.awt.Component;
import java.awt.Toolkit;
import java.math.BigDecimal;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Objects;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author vagner
 */
public class CalculadoraPrestacoesViewer extends javax.swing.JFrame {

    FuncTableModelPrestacoes f = new FuncTableModelPrestacoes();
    Locale locBrazil = new Locale("pt", "BR");
    NumberFormat nfValue = NumberFormat.getInstance(locBrazil);
    NumberFormat nfInterest = NumberFormat.getInstance(locBrazil);
    NumberFormat nfIputValue = NumberFormat.getInstance(locBrazil);
    NumberFormat nfOldIputValue = NumberFormat.getInstance(locBrazil);
    Number nValue = null;
    Number nInterest = null;
    Number nInputValue = null;
    Number nOldInputValue = null;
    Calculadora c = new CalculadoraImpl();

    Double inputValue = 0d;
    Integer months = 0;
    Double interest = 0d;
    Double value = 0d;

    /**
     * Creates new form Main
     */
    public CalculadoraPrestacoesViewer() {
        initComponents();
        util.centerWindow(this);
    }
    Utils util = new Utils();

    public int exitSystem() {
        if (javax.swing.JOptionPane.showConfirmDialog(this, "Tem certeza que deseja sair?", "Calculadora de Prestações", javax.swing.JOptionPane.YES_NO_OPTION) == 0) {
            this.dispose();
            System.exit(0);
        }
        return 1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ValorBemjNumberFormatField = new br.com.lojaoriodopeixe.utils.JNumberFormatField();
        TotalParcelasjTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        JurosjTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ValorEntradajNumberFormatField2 = new br.com.lojaoriodopeixe.utils.JNumberFormatField();
        jLabel5 = new javax.swing.JLabel();
        ValorFinanciarNumberFormatField3 = new br.com.lojaoriodopeixe.utils.JNumberFormatField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable() {
            public Component prepareRenderer(TableCellRenderer renderer,
                int rowIndex, int vColIndex) {

                Component c = super.prepareRenderer(renderer, rowIndex, vColIndex);
                if (months > 9) {
                    // altera a cor de background da linha para vermelho e foreground para branco
                    // quando o valor da coluna 3 for igual a fechado
                    if (jTable3.getValueAt(rowIndex, 0).toString().equals(months + "ª Parcela(s)")) {
                        c.setBackground(new Color(192, 0, 0));
                        c.setForeground(Color.white);
                    } else {
                        // mantem a cor padrão de foreground
                        c.setForeground(getForeground());

                        // determina a cor de background da linha selecionada
                        if (isCellSelected(rowIndex, vColIndex)) {
                            c.setBackground(new Color(184, 207, 229));
                        } else {
                            // linhas não selecionadas, manter cor de background padrão
                            c.setBackground(getBackground());
                        }

                    }
                } else {// altera a cor de background da linha para vermelho e foreground para branco
                    // quando o valor da coluna 3 for igual a fechado
                    if (jTable3.getValueAt(rowIndex, 0).toString().equals("0" + months + "ª Parcela(s)"

                    )) {
                        c.setBackground(new Color(192, 0, 0));
                        c.setForeground(Color.white);
                    }else {
                        // mantem a cor padrão de foreground
                        c.setForeground(getForeground());

                        // determina a cor de background da linha selecionada
                        if (isCellSelected(rowIndex, vColIndex)) {
                            c.setBackground(new Color(184, 207, 229));
                        } else {
                            // linhas não selecionadas, manter cor de background padrão
                            c.setBackground(getBackground());
                        }}}
                        return c;}}
                ;
                barraMenu = new javax.swing.JMenuBar();
                barraMenuArquivo = new javax.swing.JMenu();
                barraMenuCalcPrest = new javax.swing.JMenuItem();
                barraMenuCalcVista = new javax.swing.JMenuItem();
                barraMenuSimul = new javax.swing.JMenuItem();
                barraMenuSeparador = new javax.swing.JPopupMenu.Separator();
                barraMenuSair = new javax.swing.JMenuItem();
                barraMenuAjuda = new javax.swing.JMenu();
                barraMenuItemSobre = new javax.swing.JMenuItem();

                jTable2.setModel(new javax.swing.table.DefaultTableModel(
                    new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                    },
                    new String [] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                    }
                ));
                jScrollPane1.setViewportView(jTable2);

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
                setTitle("Cálculo de Prestações (Financiamento)");
                setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/mono.png")));
                setResizable(false);

                jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                jLabel1.setText("Valor do Bem R$");

                ValorBemjNumberFormatField.setText("0,01");
                ValorBemjNumberFormatField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                ValorBemjNumberFormatField.setValue(new BigDecimal(0));
                ValorBemjNumberFormatField.addFocusListener(new java.awt.event.FocusAdapter() {
                    public void focusGained(java.awt.event.FocusEvent evt) {
                        ValorBemjNumberFormatFieldFocusGained(evt);
                    }
                });
                ValorBemjNumberFormatField.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        ValorBemjNumberFormatFieldActionPerformed(evt);
                    }
                });
                ValorBemjNumberFormatField.addKeyListener(new java.awt.event.KeyAdapter() {
                    public void keyPressed(java.awt.event.KeyEvent evt) {
                        ValorBemjNumberFormatFieldKeyPressed(evt);
                    }
                    public void keyReleased(java.awt.event.KeyEvent evt) {
                        ValorBemjNumberFormatFieldKeyReleased(evt);
                    }
                    public void keyTyped(java.awt.event.KeyEvent evt) {
                        ValorBemjNumberFormatFieldKeyTyped(evt);
                    }
                });

                TotalParcelasjTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                TotalParcelasjTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
                TotalParcelasjTextField.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        TotalParcelasjTextFieldActionPerformed(evt);
                    }
                });
                TotalParcelasjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
                    public void keyTyped(java.awt.event.KeyEvent evt) {
                        TotalParcelasjTextFieldKeyTyped(evt);
                    }
                });

                jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                jLabel2.setText("Total de Parcelas");

                JurosjTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                JurosjTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
                JurosjTextField.setPreferredSize(new java.awt.Dimension(6, 26));
                JurosjTextField.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        JurosjTextFieldActionPerformed(evt);
                    }
                });
                JurosjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
                    public void keyReleased(java.awt.event.KeyEvent evt) {
                        JurosjTextFieldKeyReleased(evt);
                    }
                });

                jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                jLabel3.setText("Juros ao Mês");

                jTextField3.setEditable(false);
                jTextField3.setBackground(new java.awt.Color(255, 255, 255));
                jTextField3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                jTextField3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
                jTextField3.setFocusable(false);

                jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                jLabel4.setText("CET a.a. %");

                ValorEntradajNumberFormatField2.setText("jNumberFormatField1");
                ValorEntradajNumberFormatField2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                ValorEntradajNumberFormatField2.setValue(new BigDecimal(0));
                ValorEntradajNumberFormatField2.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        ValorEntradajNumberFormatField2ActionPerformed(evt);
                    }
                });
                ValorEntradajNumberFormatField2.addKeyListener(new java.awt.event.KeyAdapter() {
                    public void keyPressed(java.awt.event.KeyEvent evt) {
                        ValorEntradajNumberFormatField2KeyPressed(evt);
                    }
                    public void keyReleased(java.awt.event.KeyEvent evt) {
                        ValorEntradajNumberFormatField2KeyReleased(evt);
                    }
                });

                jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                jLabel5.setText("Valor da Entrada R$");

                ValorFinanciarNumberFormatField3.setText("jNumberFormatField1");
                ValorFinanciarNumberFormatField3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                ValorFinanciarNumberFormatField3.setValue(new BigDecimal(0));
                ValorFinanciarNumberFormatField3.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        ValorFinanciarNumberFormatField3ActionPerformed(evt);
                    }
                });
                ValorFinanciarNumberFormatField3.addKeyListener(new java.awt.event.KeyAdapter() {
                    public void keyPressed(java.awt.event.KeyEvent evt) {
                        ValorFinanciarNumberFormatField3KeyPressed(evt);
                    }
                });

                jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                jLabel6.setText("Valor a Financiar R$");

                jButton1.setBackground(new java.awt.Color(51, 102, 255));
                jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
                jButton1.setForeground(new java.awt.Color(255, 255, 255));
                jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculator.png"))); // NOI18N
                jButton1.setText("Calcular");
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton1ActionPerformed(evt);
                    }
                });
                jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
                    public void keyPressed(java.awt.event.KeyEvent evt) {
                        jButton1KeyPressed(evt);
                    }
                });

                jTable3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                jTable3.setModel(f);
                jTable3.setRowHeight(23);
                jScrollPane3.setViewportView(jTable3);

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(ValorBemjNumberFormatField, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1))
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TotalParcelasjTextField)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(27, 27, 27)
                                                .addComponent(jLabel3))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(JurosjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5)
                                            .addComponent(ValorEntradajNumberFormatField2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ValorFinanciarNumberFormatField3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGap(0, 104, Short.MAX_VALUE)
                                                .addComponent(jLabel6)
                                                .addGap(1, 1, 1)))))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap())
                );
                jPanel1Layout.setVerticalGroup(
                    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TotalParcelasjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JurosjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ValorBemjNumberFormatField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ValorEntradajNumberFormatField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ValorFinanciarNumberFormatField3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                );

                barraMenu.setMaximumSize(new java.awt.Dimension(90, 200));

                barraMenuArquivo.setText("Arquivo");

                barraMenuCalcPrest.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_MASK));
                barraMenuCalcPrest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calc.png"))); // NOI18N
                barraMenuCalcPrest.setText("Cálculo de Prestações");
                barraMenuCalcPrest.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        barraMenuCalcPrestActionPerformed(evt);
                    }
                });
                barraMenuArquivo.add(barraMenuCalcPrest);

                barraMenuCalcVista.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_MASK));
                barraMenuCalcVista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calc2.png"))); // NOI18N
                barraMenuCalcVista.setText("Cálculo para Valor à Vista");
                barraMenuCalcVista.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        barraMenuCalcVistaActionPerformed(evt);
                    }
                });
                barraMenuArquivo.add(barraMenuCalcVista);

                barraMenuSimul.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.CTRL_MASK));
                barraMenuSimul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calc3.png"))); // NOI18N
                barraMenuSimul.setText("Simulador de Entrada");
                barraMenuSimul.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        barraMenuSimulActionPerformed(evt);
                    }
                });
                barraMenuArquivo.add(barraMenuSimul);
                barraMenuArquivo.add(barraMenuSeparador);

                barraMenuSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
                barraMenuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit.png"))); // NOI18N
                barraMenuSair.setText("Sair");
                barraMenuSair.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        barraMenuSairActionPerformed(evt);
                    }
                });
                barraMenuArquivo.add(barraMenuSair);

                barraMenu.add(barraMenuArquivo);

                barraMenuAjuda.setText("Ajuda");

                barraMenuItemSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/about-us.png"))); // NOI18N
                barraMenuItemSobre.setText("Sobre");
                barraMenuItemSobre.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        barraMenuItemSobreActionPerformed(evt);
                    }
                });
                barraMenuAjuda.add(barraMenuItemSobre);

                barraMenu.add(barraMenuAjuda);

                setJMenuBar(barraMenu);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                );
                layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                );

                pack();
            }// </editor-fold>//GEN-END:initComponents

    private void ValorBemjNumberFormatFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValorBemjNumberFormatFieldActionPerformed
        this.ValorEntradajNumberFormatField2.requestFocusInWindow();
    }//GEN-LAST:event_ValorBemjNumberFormatFieldActionPerformed

    private void ValorEntradajNumberFormatField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValorEntradajNumberFormatField2ActionPerformed
        this.TotalParcelasjTextField.requestFocusInWindow();
    }//GEN-LAST:event_ValorEntradajNumberFormatField2ActionPerformed

    private void ValorFinanciarNumberFormatField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValorFinanciarNumberFormatField3ActionPerformed
        this.jButton1.requestFocusInWindow();
    }//GEN-LAST:event_ValorFinanciarNumberFormatField3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            nValue = nfValue.parse(ValorFinanciarNumberFormatField3.getText());
            nInterest = nfInterest.parse(JurosjTextField.getText());
            nInputValue = nfIputValue.parse(ValorEntradajNumberFormatField2.getText());

            value = nValue.doubleValue();
            interest = nInterest.doubleValue();
            months = Integer.parseInt(TotalParcelasjTextField.getText());
            inputValue = nInputValue.doubleValue();

            List<ParcelaPrestacoes> parcelas = new ArrayList<>();

            System.out.println("Resultado: " + c.calculoPrestacoes(value, interest, months, 0d));

            for (int i = 0; i < months * 2; ++i) {
                ParcelaPrestacoes parcela = new ParcelaPrestacoes();
                if (i > 1) {
                    DecimalFormat decFormat = new DecimalFormat("¤ #,###,##0.00");
                    if (i < 10) {
                        parcela.setNumero("0" + i + "ª Parcela(s)");
                    } else {
                        parcela.setNumero(i + "ª Parcela(s)");
                    }
                    parcela.setParcela(String.valueOf(decFormat.format(c.calculoPrestacoes(value, interest, i, 0d))));
                    parcela.setTotalParcelado(String.valueOf(decFormat.format(c.calculoPrestacoes(value, interest, i, 0d).multiply(new BigDecimal(i)).add(new BigDecimal(inputValue)))));
                    parcela.setTotalGeral(String.valueOf(decFormat.format(c.calculoPrestacoes(value, interest, i, 0d).multiply(new BigDecimal(i)).add(new BigDecimal(0d)))));
                    parcelas.add(parcela);
                } 
            }
            f.limpar();
            f.addListaDeParcelas(parcelas);
        } catch (ParseException | NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Um ou mais valores não informados ou incompatíveis!", "Atenção!", 2);
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ValorBemjNumberFormatFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ValorBemjNumberFormatFieldKeyPressed

    }//GEN-LAST:event_ValorBemjNumberFormatFieldKeyPressed

    private void ValorEntradajNumberFormatField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ValorEntradajNumberFormatField2KeyPressed

    }//GEN-LAST:event_ValorEntradajNumberFormatField2KeyPressed

    private void ValorFinanciarNumberFormatField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ValorFinanciarNumberFormatField3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ValorFinanciarNumberFormatField3KeyPressed

    private void ValorBemjNumberFormatFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ValorBemjNumberFormatFieldKeyTyped

    }//GEN-LAST:event_ValorBemjNumberFormatFieldKeyTyped

    private void ValorBemjNumberFormatFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ValorBemjNumberFormatFieldKeyReleased

        try {
            nInputValue = nfIputValue.parse(ValorBemjNumberFormatField.getText());
            nValue = nfValue.parse(ValorFinanciarNumberFormatField3.getText());
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Valor informado não é compativel!", "Atenção!", 2);
            System.out.println(ex.getMessage());
        }
        Double bem = nInputValue.doubleValue();
        Double financiamento = nValue.doubleValue();
        Double realValue = null;
        if (!Objects.equals(bem, financiamento)) {
            realValue = bem + 0;
        } else {
            realValue = financiamento + 0;
        }
        DecimalFormat decFormat = new DecimalFormat("¤ #,###,##0.00");

        ValorFinanciarNumberFormatField3.setText(String.valueOf(decFormat.format(realValue)));
    }//GEN-LAST:event_ValorBemjNumberFormatFieldKeyReleased

    private void ValorEntradajNumberFormatField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ValorEntradajNumberFormatField2KeyReleased
        try {
            nInputValue = nfIputValue.parse(ValorEntradajNumberFormatField2.getText());
            nValue = nfValue.parse(ValorBemjNumberFormatField.getText());
            nOldInputValue = nfOldIputValue.parse(ValorFinanciarNumberFormatField3.getText());
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Valor informado não é compativel!", "Atenção!", 2);
            System.out.println(ex.getMessage());
        }
        DecimalFormat decFormat = new DecimalFormat("¤ #,###,##0.00");
        Double entrada = nInputValue.doubleValue();
        Double financiamento = nValue.doubleValue();
        if (entrada > financiamento) {
            JOptionPane.showMessageDialog(this, "Valor da entrada é maior ou igual ao Financiamento!", "Atenção!", 2);
            Double aux = nOldInputValue.doubleValue();
            ValorFinanciarNumberFormatField3.setText(String.valueOf(decFormat.format(aux)));
            ValorEntradajNumberFormatField2.setText("");
        }
        Double realValue = financiamento - entrada;
        ValorFinanciarNumberFormatField3.setText(String.valueOf(decFormat.format(realValue)));
    }//GEN-LAST:event_ValorEntradajNumberFormatField2KeyReleased

    private void TotalParcelasjTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TotalParcelasjTextFieldKeyTyped
        String caracteres = "0987654321";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_TotalParcelasjTextFieldKeyTyped

    private void TotalParcelasjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalParcelasjTextFieldActionPerformed
        this.JurosjTextField.requestFocusInWindow();
    }//GEN-LAST:event_TotalParcelasjTextFieldActionPerformed

    private void JurosjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JurosjTextFieldActionPerformed
        this.jButton1.requestFocusInWindow();
    }//GEN-LAST:event_JurosjTextFieldActionPerformed

    private void JurosjTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JurosjTextFieldKeyReleased
        try {
            if (!"".equals(JurosjTextField.getText())) {
                nInterest = nfInterest.parse(JurosjTextField.getText());
            } else {nInterest = nfInterest.parse("0.00");}
        } catch (ParseException ex) {
            Logger.getLogger(CalculadoraPrestacoesViewer.class.getName()).log(Level.SEVERE, null, ex);
        }
        interest = nInterest.doubleValue();
        if (!"0,00".equals(ValorBemjNumberFormatField.getText())) {
            jTextField3.setText(String.valueOf(c.calculoCetReal(interest)).replace(".", ","));
        }

    }//GEN-LAST:event_JurosjTextFieldKeyReleased

    private void ValorBemjNumberFormatFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ValorBemjNumberFormatFieldFocusGained
        ValorBemjNumberFormatField.selectAll();
    }//GEN-LAST:event_ValorBemjNumberFormatFieldFocusGained

    private void barraMenuCalcPrestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraMenuCalcPrestActionPerformed
        this.dispose();
        CalculadoraPrestacoesViewer cpv = new CalculadoraPrestacoesViewer();
        cpv.setVisible(true);
    }//GEN-LAST:event_barraMenuCalcPrestActionPerformed

    private void barraMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraMenuSairActionPerformed
        exitSystem();
    }//GEN-LAST:event_barraMenuSairActionPerformed

    private void barraMenuItemSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraMenuItemSobreActionPerformed
        JOptionPane.showConfirmDialog( null," Desenvolvido em conjunto por: \n Vagner Barbosa e Solon Diego", "Sobre",JOptionPane.CLOSED_OPTION);
    }//GEN-LAST:event_barraMenuItemSobreActionPerformed

    private void barraMenuCalcVistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraMenuCalcVistaActionPerformed
        this.dispose();
        CalculadoraAVistaViewer cav = new CalculadoraAVistaViewer();
        cav.setVisible(true);
    }//GEN-LAST:event_barraMenuCalcVistaActionPerformed

    private void barraMenuSimulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraMenuSimulActionPerformed
        this.dispose();
        CalculadoraSimulacaoViewer csv = new CalculadoraSimulacaoViewer();
        csv.setVisible(true);
    }//GEN-LAST:event_barraMenuSimulActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        try {
            nValue = nfValue.parse(ValorFinanciarNumberFormatField3.getText());
            nInterest = nfInterest.parse(JurosjTextField.getText());
            nInputValue = nfIputValue.parse(ValorEntradajNumberFormatField2.getText());

            value = nValue.doubleValue();
            interest = nInterest.doubleValue();
            months = Integer.parseInt(TotalParcelasjTextField.getText());
            inputValue = nInputValue.doubleValue();

            List<ParcelaPrestacoes> parcelas = new ArrayList<>();

            System.out.println("Resultado: " + c.calculoPrestacoes(value, interest, months, 0d));

            for (int i = 0; i < months * 2; ++i) {
                ParcelaPrestacoes parcela = new ParcelaPrestacoes();
                if (i > 1) {
                    DecimalFormat decFormat = new DecimalFormat("¤ #,###,##0.00");
                    if (i < 10) {
                        parcela.setNumero("0" + i + "ª Parcela(s)");
                    } else {
                        parcela.setNumero(i + "ª Parcela(s)");
                    }
                    parcela.setParcela(String.valueOf(decFormat.format(c.calculoPrestacoes(value, interest, i, 0d))));
                    parcela.setTotalParcelado(String.valueOf(decFormat.format(c.calculoPrestacoes(value, interest, i, 0d).multiply(new BigDecimal(i)).add(new BigDecimal(inputValue)))));
                    parcela.setTotalGeral(String.valueOf(decFormat.format(c.calculoPrestacoes(value, interest, i, 0d).multiply(new BigDecimal(i)).add(new BigDecimal(0d)))));
                    parcelas.add(parcela);
                } 
            }
            f.limpar();
            f.addListaDeParcelas(parcelas);
        } catch (ParseException | NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Um ou mais valores não informados ou incompatíveis!", "Atenção!", 2);
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jButton1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    javax.swing.UIManager.put("control", new Color(248, 248, 255));
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraPrestacoesViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new CalculadoraPrestacoesViewer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JurosjTextField;
    private javax.swing.JTextField TotalParcelasjTextField;
    private br.com.lojaoriodopeixe.utils.JNumberFormatField ValorBemjNumberFormatField;
    private br.com.lojaoriodopeixe.utils.JNumberFormatField ValorEntradajNumberFormatField2;
    private br.com.lojaoriodopeixe.utils.JNumberFormatField ValorFinanciarNumberFormatField3;
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenu barraMenuAjuda;
    private javax.swing.JMenu barraMenuArquivo;
    private javax.swing.JMenuItem barraMenuCalcPrest;
    private javax.swing.JMenuItem barraMenuCalcVista;
    private javax.swing.JMenuItem barraMenuItemSobre;
    private javax.swing.JMenuItem barraMenuSair;
    private javax.swing.JPopupMenu.Separator barraMenuSeparador;
    private javax.swing.JMenuItem barraMenuSimul;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
