package br.com.lojaoriodopeixe.visao;

import br.com.lojaoriodopeixe.controle.CalculadoraImpl;
import br.com.lojaoriodopeixe.utils.ParcTableModelAVista;
import br.com.lojaoriodopeixe.utils.Utils;
import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 * Classe de visão CalculadoraSelecaoViewer.
 *
 * @author Vagner Barbosa (contato@vagnerbarbosa.com)
 *
 * @since 10/11/2017
 *
 * @version 1.0
 */
public class CalculadoraSelecaoViewer extends javax.swing.JFrame {
    
    public static CalculadoraPrestacoesViewer cpv = null;
    public static CalculadoraAVistaViewer cav = null;
    public static CalculadoraSimulacaoViewer csv = null;
    public static CalculadoraSobreViewer cssv = null;

    public CalculadoraSelecaoViewer() {
        initComponents();
        util.centerWindow(this);
    }
    
    public int exitSystem() {
        if (javax.swing.JOptionPane.showConfirmDialog(this, "Tem certeza que deseja sair?", "Calculadora de Prestações", javax.swing.JOptionPane.YES_NO_OPTION) == 0) {
            this.dispose();
            System.exit(0);
        }
        return 1;
    }
    
    Utils util = new Utils();
    CalculadoraImpl ci = new CalculadoraImpl();
    ParcTableModelAVista f = new ParcTableModelAVista();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CalculoPrestacoes = new javax.swing.JButton();
        CalculoPrestacoes1 = new javax.swing.JButton();
        CalculoPrestacoes2 = new javax.swing.JButton();
        barraMenu = new javax.swing.JMenuBar();
        barraMenuArquivo = new javax.swing.JMenu();
        barraMenuCalcPrest = new javax.swing.JMenuItem();
        barraMenuCalcVista = new javax.swing.JMenuItem();
        barraMenuSimul = new javax.swing.JMenuItem();
        barraMenuSeparador = new javax.swing.JPopupMenu.Separator();
        barraMenuSair = new javax.swing.JMenuItem();
        barraMenuAjuda = new javax.swing.JMenu();
        barraMenuItemSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora LRP");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/mono.png")));
        setIconImages(getIconImages());
        setLocationByPlatform(true);
        setResizable(false);

        CalculoPrestacoes.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        CalculoPrestacoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calc.png"))); // NOI18N
        CalculoPrestacoes.setText("Cálculo de Prestações");
        CalculoPrestacoes.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        CalculoPrestacoes.setPreferredSize(new java.awt.Dimension(240, 33));
        CalculoPrestacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculoPrestacoesActionPerformed(evt);
            }
        });

        CalculoPrestacoes1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        CalculoPrestacoes1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calc2.png"))); // NOI18N
        CalculoPrestacoes1.setText("Cálculo para Valor à Vista");
        CalculoPrestacoes1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        CalculoPrestacoes1.setPreferredSize(new java.awt.Dimension(240, 33));
        CalculoPrestacoes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculoPrestacoes1ActionPerformed(evt);
            }
        });

        CalculoPrestacoes2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        CalculoPrestacoes2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calc3.png"))); // NOI18N
        CalculoPrestacoes2.setText("Sugestão de Entrada");
        CalculoPrestacoes2.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        CalculoPrestacoes2.setPreferredSize(new java.awt.Dimension(240, 33));
        CalculoPrestacoes2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculoPrestacoes2ActionPerformed(evt);
            }
        });

        barraMenu.setMaximumSize(new java.awt.Dimension(90, 200));

        barraMenuArquivo.setText("Funções");

        barraMenuCalcPrest.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_MASK));
        barraMenuCalcPrest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calc.png"))); // NOI18N
        barraMenuCalcPrest.setText("Cálculo de Prestações");
        barraMenuCalcPrest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barraMenuCalcPrestActionPerformed(evt);
            }
        });
        barraMenuArquivo.add(barraMenuCalcPrest);

        barraMenuCalcVista.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_MASK));
        barraMenuCalcVista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calc2.png"))); // NOI18N
        barraMenuCalcVista.setText("Cálculo para Valor à Vista");
        barraMenuCalcVista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barraMenuCalcVistaActionPerformed(evt);
            }
        });
        barraMenuArquivo.add(barraMenuCalcVista);

        barraMenuSimul.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.CTRL_MASK));
        barraMenuSimul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calc3.png"))); // NOI18N
        barraMenuSimul.setText("Sugestão de Entrada");
        barraMenuSimul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barraMenuSimulActionPerformed(evt);
            }
        });
        barraMenuArquivo.add(barraMenuSimul);
        barraMenuArquivo.add(barraMenuSeparador);

        barraMenuSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        barraMenuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit.png"))); // NOI18N
        barraMenuSair.setText("Sair");
        barraMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barraMenuSairActionPerformed(evt);
            }
        });
        barraMenuArquivo.add(barraMenuSair);

        barraMenu.add(barraMenuArquivo);

        barraMenuAjuda.setText("Ajuda");

        barraMenuItemSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/about-us.png"))); // NOI18N
        barraMenuItemSobre.setText("Sobre");
        barraMenuItemSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barraMenuItemSobreActionPerformed(evt);
            }
        });
        barraMenuAjuda.add(barraMenuItemSobre);

        barraMenu.add(barraMenuAjuda);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CalculoPrestacoes1, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                    .addComponent(CalculoPrestacoes2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CalculoPrestacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(CalculoPrestacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CalculoPrestacoes1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CalculoPrestacoes2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void barraMenuCalcPrestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraMenuCalcPrestActionPerformed
        if (cpv == null) {
            cpv = new CalculadoraPrestacoesViewer();
            cpv.setVisible(true);
        } else {
            cpv.setVisible(true);
        }
    }//GEN-LAST:event_barraMenuCalcPrestActionPerformed

    private void barraMenuItemSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraMenuItemSobreActionPerformed
        if (cssv == null) {
        cssv = new CalculadoraSobreViewer();
        cssv.setVisible(true);
        } else {
        cssv.setVisible(true);
        }
    }//GEN-LAST:event_barraMenuItemSobreActionPerformed

    private void CalculoPrestacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculoPrestacoesActionPerformed
        if (cpv == null) {
            cpv = new CalculadoraPrestacoesViewer();
            cpv.setVisible(true);
        } else {
            cpv.setVisible(true);
        }
    }//GEN-LAST:event_CalculoPrestacoesActionPerformed

    private void CalculoPrestacoes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculoPrestacoes1ActionPerformed
        if (cav == null) {
        cav = new CalculadoraAVistaViewer();
        cav.setVisible(true);
        } else {
        cav.setVisible(true);    
        }
    }//GEN-LAST:event_CalculoPrestacoes1ActionPerformed

    private void CalculoPrestacoes2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculoPrestacoes2ActionPerformed
        if (csv == null) {
            csv = new CalculadoraSimulacaoViewer();
            csv.setVisible(true);
        } else {
            csv.setVisible(true);
        }     
    }//GEN-LAST:event_CalculoPrestacoes2ActionPerformed

    private void barraMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraMenuSairActionPerformed
        exitSystem();
    }//GEN-LAST:event_barraMenuSairActionPerformed

    private void barraMenuCalcVistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraMenuCalcVistaActionPerformed
        if (cav == null) {
        cav = new CalculadoraAVistaViewer();
        cav.setVisible(true);
        } else {
            cav.setVisible(true);
        }
    }//GEN-LAST:event_barraMenuCalcVistaActionPerformed

    private void barraMenuSimulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraMenuSimulActionPerformed
        if (csv == null) {
        csv = new CalculadoraSimulacaoViewer();
        csv.setVisible(true);
        } else {
            csv.setVisible(true);
        }
    }//GEN-LAST:event_barraMenuSimulActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    javax.swing.UIManager.put("control", new Color(248, 248, 255));
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraSelecaoViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraSelecaoViewer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CalculoPrestacoes;
    private javax.swing.JButton CalculoPrestacoes1;
    private javax.swing.JButton CalculoPrestacoes2;
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenu barraMenuAjuda;
    private javax.swing.JMenu barraMenuArquivo;
    private javax.swing.JMenuItem barraMenuCalcPrest;
    private javax.swing.JMenuItem barraMenuCalcVista;
    private javax.swing.JMenuItem barraMenuItemSobre;
    private javax.swing.JMenuItem barraMenuSair;
    private javax.swing.JPopupMenu.Separator barraMenuSeparador;
    private javax.swing.JMenuItem barraMenuSimul;
    // End of variables declaration//GEN-END:variables
}
